export * from './Landing/Landing.screen';
export * from './Auth/Auth.screen';
export * from './Home/Home.screen';
export * from './NotFound/NotFound.screen';
export * from './Section/Section.screen';
export * from './Food/Food.screen';
export * from './FoodDetail/FoodDetail.screen';
export * from './Menu/Menu.screen';
export * from './Config/Config.screen';
